Grupo1
iita-robotica/competencia_2022 pull request #13
Opened 2022-05-18 03:01 UTC by Bloki2319

Subo el archivo que se vio en esta clase para mover al robot por el laberinto.

2022-05-18 23:13 UTC, URGerardo approved these changes

2022-05-24 21:15 UTC, iita-robotica requested changes
Revisar que se esta modificando el submodulo de RoboligaVirtual. Por favor deshacer ese cambio.

2022-05-31 23:15 UTC, iita-robotica requested changes
Por favor addressear comentarios.

2022-05-31 23:15 UTC, iita-robotica commented on G1Gerardo-Camila-Augusto/Grupo 1 - Avanzar, Rotar y Volver.py
> +
Hay muchas lineas en blanco, por favor dejar solo una linea en blanco.

2022-05-31 23:15 UTC, iita-robotica commented on G1Gerardo-Camila-Augusto/TP-Semáforo/Trabajo Práctico IITA - Semáforo Solución (1).py
> +print ("Programa terminado.")
dejar una linea en blanco

2022-05-31 23:15 UTC, iita-robotica commented on G1Gerardo-Camila-Augusto/TP-Semáforo/Trabajo Práctico IITA - Semáforo Solución (2).py
> +print ("Programa terminado.")
lo  mismo, dejar una linea en blanco

2022-05-31 23:25 UTC, Bloki2319 commented on G1Gerardo-Camila-Augusto/Grupo 1 - Avanzar, Rotar y Volver.py
> +
Listo profe ya lo corregi

2022-05-31 23:26 UTC, Bloki2319 commented on G1Gerardo-Camila-Augusto/TP-Semáforo/Trabajo Práctico IITA - Semáforo Solución (2).py
> +print ("Programa terminado.")
Listo profe ya lo corregi

2022-06-07 21:20 UTC, iita-robotica approved these changes

2022-06-07 21:20 UTC, merged