Agrego los ejemplos utilizados en clases
iita-robotica/competencia_2022 pull request #6
Opened 2022-05-06 12:13 UTC by lchico

Se agregaron:
* Ejemplo del uso del encoder
* Como realizar una maquina de estados
- Tarea del semafor

2022-05-10 22:13 UTC, URGerardo requested changes
Recibido.

2022-05-10 22:37 UTC, Bloki2319 reviewed
ta perfecto

2022-05-10 22:37 UTC, URGerardo approved these changes

2022-05-10 22:37 UTC, Bloki2319 approved these changes
ta perfecto x2

2022-05-10 22:41 UTC, camila155 approved these changes
Cambios aprobados

2022-05-10 22:51 UTC, Maxi-Scarponetti approved these changes

2022-05-10 22:51 UTC, SosaMiranda approved these changes

2022-05-10 23:30 UTC, iandib approved these changes

2022-05-11 00:02 UTC, iita-robotica commented
@DanturMaxi, Buenas, no te olvides de aprobar el PR, por favor :)

2022-05-17 22:41 UTC, DanturMaxi approved these changes

2022-05-17 23:19 UTC, merged